name: new_weather
channels:
- defaults
dependencies:
  - numpy=1.23.3
  - pandas=1.0.3
  - scikit-learn=0.22.1
  - cloudpickle=1.2.2
  - pip=20.0.2
  - pip:
    - mlflow
    - azure-ai-ml
    - azure-identity 
    - azureml-mlflow